baseURL = "https://codethat.today"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContenLanguageInSubdir = "true"
title = "Top Quality Developer Tutorials CodeThat.today"
Paginate = 10
pygmentsUseClasses = true
pygmentsCodeFences = true
canonifyurls = true
theme = "vsdocs"
googleAnalytics = "UA-141826516-1"
timeout=30000

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  level = "levels"

[[menu.main]]
    name = "Go"
    weight = -100
    url = "/categories/go/"
[[menu.main]]
    name = "Javascript"
    weight = -90
    url = "/categories/javascript/"
[[menu.main]]
    name = "Data Structures"
    weight = -80
    url = "/categories/data-structures/"
[[menu.main]]
    name = "Books"
    weight = -50
    url = "/books/"

[[menu.main]]
    name = "more"
    weight = -40
    url = "/"

[[menu.main]]
    parent = "more"
    name = "Development"
    weight = -100
    url = "/categories/development/"

[[menu.main]]
    parent = "more"
    name = "Architecture"
    weight = -100
    url = "/categories/architecture/"

[[menu.footer]]
    name = "About"
    weight = -100
    url = "/about"

[[menu.footer]]
    name = "Privacy Policy"
    weight = -100
    url = "https://www.iubenda.com/privacy-policy/63392594"

[Params]
  RSSLink = "/index.xml"
  author = "theodesp"
  github = "theodesp"
  twitter = "@CodeThatToday"
  email = "thdespou@hotmail.com"
  sharing = true
  dateFormatToUse = "2006-01-02"
  orgName = "CodeThat.today"
  mainSections = ["article", "tutorial"]
  copyright = "Code snippets licensed under MIT, unless otherwise noted © 2019"
  comments = { enabled = true, repo                = "theodesp/codethat" }
